# NUC980 series audio
snd-soc-nuc980-pcm-objs := nuc980-pcm.o
snd-soc-nuc980-i2s-objs := nuc980-i2s.o

obj-$(CONFIG_SND_SOC_NUC980) += snd-soc-nuc980-pcm.o nuc980-i2s.o

# Boards
snd-soc-nuc980-audio-objs := nuc980-audio.o

obj-$(CONFIG_SND_SOC_NUC980EVB) += snd-soc-nuc980-audio.o
